services:
    IDCI\Bundle\AssetLoaderBundle\AssetProvider\AssetProviderRegistry:
        class: IDCI\Bundle\AssetLoaderBundle\AssetProvider\AssetProviderRegistry

    IDCI\Bundle\AssetLoaderBundle\AssetRenderer\AssetRenderer:
        class: IDCI\Bundle\AssetLoaderBundle\AssetRenderer\AssetRenderer
        arguments:
            - '@twig'

    IDCI\Bundle\AssetLoaderBundle\AssetLoader\AssetDOMLoader:
        class: IDCI\Bundle\AssetLoaderBundle\AssetLoader\AssetDOMLoader
        arguments:
            - '@event_dispatcher'
            - '@IDCI\Bundle\AssetLoaderBundle\AssetRenderer\AssetRenderer'
            - '@IDCI\Bundle\AssetLoaderBundle\AssetProvider\AssetProviderRegistry'

    IDCI\Bundle\AssetLoaderBundle\Event\Subscriber\AssetDOMLoaderEventSubscriber:
        class: IDCI\Bundle\AssetLoaderBundle\Event\Subscriber\AssetDOMLoaderEventSubscriber
        arguments:
            - '@IDCI\Bundle\AssetLoaderBundle\AssetRenderer\AssetRenderer'
            - '@IDCI\Bundle\AssetLoaderBundle\AssetProvider\AssetProviderRegistry'
            - '%idci_asset_loader.providers.load_all%'
            - '%idci_asset_loader.providers.load_only%'
        tags:
            - { name: kernel.event_subscriber }
