version: '2'

services:

  php:
    image: idci-asset-loader-bundle/php:5.6-fpm
    build:
      context: .docker/build/php5.6
    volumes:
      - ./:/var/www/html
      - composer-cache:/root/.composer

volumes:
  composer-cache: ~
